language: python

matrix:
  include:
  - python: "3.7"  # remove workaround if travis relases 3.7 officially
    env: PY_VERSION=py37
    dist: xenial
    sudo: true
  - python: "3.8-dev"
    env: PY_VERSION=py38
  allow_failures:
  - python: "3.8-dev"

addons:
  apt:
    update: true

install:
  - pip install --upgrade -e .[dev]
  - pip install codacy-coverage codecov

script:
  - ./scripts/build.sh "$PY_VERSION"
  - nose2 -c setup.cfg -v
  - python setup.py check -v -r -m -s
  - mp3monitoring --version

after_success:
  - codecov
  - coverage xml
  - python-codacy-coverage -v -r coverage.xml

deploy:
  - provider: script
    skip_cleanup: true
    script: twine upload -u $PYPI_USER -p $PYPI_PASSWORD --skip-existing dist/*
    on:
      repo: IceflowRE/mp3monitoring
      tags: true
