# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 300)
        MainWindow.setWindowTitle("MP3 Monitoring")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../data/icon_export.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(512, 512))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.profileTree = QtWidgets.QTableWidget(self.centralWidget)
        self.profileTree.setEnabled(True)
        self.profileTree.setAutoFillBackground(False)
        self.profileTree.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.profileTree.setAlternatingRowColors(False)
        self.profileTree.setGridStyle(QtCore.Qt.SolidLine)
        self.profileTree.setObjectName("profileTree")
        self.profileTree.setColumnCount(4)
        self.profileTree.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.profileTree.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.profileTree.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.profileTree.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.profileTree.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.profileTree, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_add = QtWidgets.QAction(MainWindow)
        self.action_add.setObjectName("action_add")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_check_for_updates = QtWidgets.QAction(MainWindow)
        self.action_check_for_updates.setObjectName("action_check_for_updates")
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.menuFile.addAction(self.action_add)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_exit)
        self.menuHelp.addAction(self.action_help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_check_for_updates)
        self.menuHelp.addAction(self.action_about)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.profileTree.setSortingEnabled(True)
        item = self.profileTree.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Activ"))
        item = self.profileTree.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Source"))
        item = self.profileTree.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Target"))
        item = self.profileTree.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.action_add.setText(_translate("MainWindow", "&Add..."))
        self.action_add.setToolTip(_translate("MainWindow", "Add a directory"))
        self.action_add.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.action_exit.setText(_translate("MainWindow", "&Exit"))
        self.action_about.setText(_translate("MainWindow", "&About"))
        self.action_check_for_updates.setText(_translate("MainWindow", "Check for updates"))
        self.action_help.setText(_translate("MainWindow", "&Help"))
        self.action_help.setShortcut(_translate("MainWindow", "Ctrl+H"))

